"""
GraphRAG Pydantic 模型

所有用於 API 請求、回應、圖譜資料和攝取的 Pydantic 模型。

模型分類：
- requests: API 請求模型（VectorizeRequest, AskRequest 等）
- responses: API 回應模型（AskResponse, SSE 事件等）
- graph: 圖譜資料模型（Entity, Relation, Community 等）
- ingestion: 攝取相關模型（Document, Chunk, IngestJob 等）
"""

from chatbot_graphrag.models.pydantic.requests import (
    VectorizeRequest,
    VectorizeStatusRequest,
    AskRequest,
    AskStreamChatRequest,
    HITLResolveRequest,
    FeedbackRequest,
    CacheInvalidateRequest,
    GraphQueryRequest,
    CommunityReportRequest,
)

from chatbot_graphrag.models.pydantic.responses import (
    BaseResponse,
    ErrorResponse,
    VectorizeResponse,
    VectorizeStatusResponse,
    Citation,
    EvidenceItem,
    RetrievalMetrics,
    LoopMetrics,
    AskResponse,
    SSEEvent,
    SSEGuardEvent,
    SSEIntentEvent,
    SSERetrievalEvent,
    SSEGroundednessEvent,
    SSEResponseChunk,
    SSEMetaSummary,
    HITLResolveResponse,
    HITLPendingResponse,
    FeedbackResponse,
    CacheInvalidateResponse,
    CacheStatsResponse,
    GraphQueryResponse,
    CommunityReportResponse,
    HealthResponse,
    ServiceHealth,
)

from chatbot_graphrag.models.pydantic.graph import (
    EntityBase,
    Entity,
    EntityCreate,
    EntityMerge,
    RelationBase,
    Relation,
    RelationCreate,
    EventBase,
    Event,
    EventCreate,
    CommunityBase,
    Community,
    CommunityReport,
    CommunityCreate,
    Subgraph,
    GraphTraversalResult,
    ExtractedEntity,
    ExtractedRelation,
    ExtractionResult,
)

from chatbot_graphrag.models.pydantic.ingestion import (
    DocumentMetadata,
    DocumentInput,
    Document,
    DocumentVersion,
    ChunkMetadata,
    Chunk,
    ChunkCreate,
    ChunkArtifact,
    IngestJobConfig,
    IngestJob,
    IngestJobUpdate,
    PipelineStageResult,
    PipelineResult,
    IndexVersion,
    TraceLink,
    CuratedDocSchema,
)

__all__ = [
    # ==================== 請求模型 ====================
    "VectorizeRequest",
    "VectorizeStatusRequest",
    "AskRequest",
    "AskStreamChatRequest",
    "HITLResolveRequest",
    "FeedbackRequest",
    "CacheInvalidateRequest",
    "GraphQueryRequest",
    "CommunityReportRequest",
    # ==================== 回應模型 ====================
    "BaseResponse",
    "ErrorResponse",
    "VectorizeResponse",
    "VectorizeStatusResponse",
    "Citation",
    "EvidenceItem",
    "RetrievalMetrics",
    "LoopMetrics",
    "AskResponse",
    "SSEEvent",
    "SSEGuardEvent",
    "SSEIntentEvent",
    "SSERetrievalEvent",
    "SSEGroundednessEvent",
    "SSEResponseChunk",
    "SSEMetaSummary",
    "HITLResolveResponse",
    "HITLPendingResponse",
    "FeedbackResponse",
    "CacheInvalidateResponse",
    "CacheStatsResponse",
    "GraphQueryResponse",
    "CommunityReportResponse",
    "HealthResponse",
    "ServiceHealth",
    # ==================== 圖譜模型 ====================
    "EntityBase",
    "Entity",
    "EntityCreate",
    "EntityMerge",
    "RelationBase",
    "Relation",
    "RelationCreate",
    "EventBase",
    "Event",
    "EventCreate",
    "CommunityBase",
    "Community",
    "CommunityReport",
    "CommunityCreate",
    "Subgraph",
    "GraphTraversalResult",
    "ExtractedEntity",
    "ExtractedRelation",
    "ExtractionResult",
    # ==================== 攝取模型 ====================
    "DocumentMetadata",
    "DocumentInput",
    "Document",
    "DocumentVersion",
    "ChunkMetadata",
    "Chunk",
    "ChunkCreate",
    "ChunkArtifact",
    "IngestJobConfig",
    "IngestJob",
    "IngestJobUpdate",
    "PipelineStageResult",
    "PipelineResult",
    "IndexVersion",
    "TraceLink",
    "CuratedDocSchema",
]
